module_name: Tracking - Front Office
compatible_versions: 1.0.0+
author: thirty bees
category: back office
tags:
  - affiliates
  - statistics
  - referrers
description_short: Enables your affiliates to access their own statistics. See Stats/Referrers.
description: description.md
images:
  - image-1.png
license: AFL 3.0
